/* eslint-disable no-console */
import { PrismaClient, Prisma } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

// Based on SAMPLE_PROFILES from the prototype (prototype/js/data.js), trimmed to the fields our
// schema exposes. The real build should seed 30 — we seed 10 for speed and variety.
const SAMPLES = [
  {
    email: 'priya.sharma@example.com',
    phone: '+919900010001',
    fullName: 'Priya Sharma',
    gender: 'FEMALE' as const,
    dob: '1998-04-12',
    height: "5'4\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Hindi',
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Gaur',
    gotra: 'Kashyap',
    manglik: 'NO' as const,
    rashi: 'Vrishabha (Taurus)',
    nakshatra: 'Rohini',
    education: 'M.Tech (Computer Science)',
    occupation: 'Software Engineer',
    income: '₹14 LPA',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    diet: 'VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'NO' as const,
    aboutMe:
      'Family-oriented, calm by nature, love reading, classical music and travelling. Looking for a kind, educated and respectful life partner.',
    familyValues: 'TRADITIONAL' as const,
    hobbies: ['Reading', 'Classical music', 'Travel'],
    languages: ['Hindi', 'English'],
    personalityTraits: ['Calm', 'Family-oriented', 'Thoughtful'],
  },
  {
    email: 'rahul.verma@example.com',
    phone: '+919900010002',
    fullName: 'Rahul Verma',
    gender: 'MALE' as const,
    dob: '1994-09-08',
    height: "5'10\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Hindi',
    religion: 'Hindu',
    caste: 'Kshatriya',
    subCaste: 'Rajput',
    gotra: 'Suryavanshi',
    manglik: 'YES' as const,
    education: 'MBA (IIM Bangalore)',
    occupation: 'Product Manager',
    income: '₹38 LPA',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'India',
    diet: 'NON_VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'OCCASIONALLY' as const,
    aboutMe:
      'Easygoing, ambitious and family loving. Enjoy cricket, weekend treks and good food. Searching for an understanding partner.',
    familyValues: 'MODERATE' as const,
    hobbies: ['Cricket', 'Trekking', 'Cooking'],
    languages: ['Hindi', 'English'],
    personalityTraits: ['Ambitious', 'Easygoing', 'Adventurous'],
  },
  {
    email: 'anjali.patel@example.com',
    phone: '+919900010003',
    fullName: 'Anjali Patel',
    gender: 'FEMALE' as const,
    dob: '2000-11-23',
    height: "5'3\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Gujarati',
    religion: 'Hindu',
    caste: 'Patel',
    subCaste: 'Leuva Patel',
    manglik: 'NO' as const,
    education: 'CA (Chartered Accountant)',
    occupation: 'Auditor',
    income: '₹11 LPA',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    diet: 'VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'NO' as const,
    aboutMe:
      'Cheerful, hardworking, value family and traditions. Love cooking, classical dance and gardening.',
    familyValues: 'TRADITIONAL' as const,
    hobbies: ['Cooking', 'Classical dance', 'Gardening'],
    languages: ['Gujarati', 'Hindi', 'English'],
    personalityTraits: ['Cheerful', 'Hardworking', 'Traditional'],
  },
  {
    email: 'arjun.reddy@example.com',
    phone: '+919900010004',
    fullName: 'Arjun Reddy',
    gender: 'MALE' as const,
    dob: '1996-06-15',
    height: "6'0\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Telugu',
    religion: 'Hindu',
    caste: 'Reddy',
    manglik: 'NO' as const,
    education: 'B.Tech, MS (Stanford)',
    occupation: 'Senior Software Engineer',
    income: '₹95 LPA',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    diet: 'NON_VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'OCCASIONALLY' as const,
    aboutMe: 'Tech enthusiast, fitness freak, love road trips. Believe in simplicity and honesty.',
    familyValues: 'MODERATE' as const,
    hobbies: ['Tech', 'Fitness', 'Road trips'],
    languages: ['Telugu', 'Hindi', 'English'],
    personalityTraits: ['Honest', 'Ambitious', 'Tech-savvy'],
  },
  {
    email: 'kavya.iyer@example.com',
    phone: '+919900010005',
    fullName: 'Kavya Iyer',
    gender: 'FEMALE' as const,
    dob: '1997-02-28',
    height: "5'5\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Tamil',
    religion: 'Hindu',
    caste: 'Iyer',
    subCaste: 'Vadama',
    manglik: 'NO' as const,
    education: 'M.Sc Physics, PhD (Ongoing)',
    occupation: 'Research Scholar',
    income: '₹8 LPA',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    diet: 'VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'NO' as const,
    aboutMe: 'Curious, calm and devoted to learning. Love Carnatic music, cooking, and temple visits.',
    familyValues: 'TRADITIONAL' as const,
    hobbies: ['Carnatic music', 'Cooking', 'Temple visits'],
    languages: ['Tamil', 'English'],
    personalityTraits: ['Calm', 'Curious', 'Devoted'],
  },
  {
    email: 'vikram.singh@example.com',
    phone: '+919900010006',
    fullName: 'Vikram Singh',
    gender: 'MALE' as const,
    dob: '1992-12-04',
    height: "5'11\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Punjabi',
    religion: 'Sikh',
    caste: 'Jat',
    subCaste: 'Sandhu',
    manglik: 'NO' as const,
    education: 'MBBS, MD (Cardiology)',
    occupation: 'Doctor',
    income: '₹28 LPA',
    city: 'Chandigarh',
    state: 'Chandigarh',
    country: 'India',
    diet: 'NON_VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'NO' as const,
    aboutMe: 'Disciplined, family-loving and dedicated to my profession. Love Gurbani and morning runs.',
    familyValues: 'TRADITIONAL' as const,
    hobbies: ['Gurbani', 'Running', 'Medicine'],
    languages: ['Punjabi', 'Hindi', 'English'],
    personalityTraits: ['Disciplined', 'Dedicated', 'Family-loving'],
  },
  {
    email: 'sneha.joshi@example.com',
    phone: '+919900010007',
    fullName: 'Sneha Joshi',
    gender: 'FEMALE' as const,
    dob: '1999-07-19',
    height: "5'2\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Marathi',
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Deshastha',
    manglik: 'YES' as const,
    education: 'B.Arch, M.Arch',
    occupation: 'Architect',
    income: '₹9 LPA',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    diet: 'VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'NO' as const,
    aboutMe: 'Creative, independent, love sketching, Marathi literature and morning yoga.',
    familyValues: 'MODERATE' as const,
    hobbies: ['Sketching', 'Yoga', 'Literature'],
    languages: ['Marathi', 'Hindi', 'English'],
    personalityTraits: ['Creative', 'Independent', 'Thoughtful'],
  },
  {
    email: 'rohan.kapoor@example.com',
    phone: '+919900010008',
    fullName: 'Rohan Kapoor',
    gender: 'MALE' as const,
    dob: '1995-03-30',
    height: "5'9\"",
    maritalStatus: 'NEVER_MARRIED' as const,
    motherTongue: 'Hindi',
    religion: 'Hindu',
    caste: 'Khatri',
    subCaste: 'Kapoor',
    manglik: 'NO' as const,
    education: 'B.Com, CA',
    occupation: 'Finance Manager',
    income: '₹22 LPA',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    diet: 'VEGETARIAN' as const,
    smoking: 'NO' as const,
    drinking: 'NO' as const,
    aboutMe: 'Fun-loving, family-oriented, foodie. Enjoy Bollywood, board games and Sunday brunches.',
    familyValues: 'MODERATE' as const,
    hobbies: ['Bollywood', 'Board games', 'Food'],
    languages: ['Hindi', 'English'],
    personalityTraits: ['Fun-loving', 'Family-oriented', 'Foodie'],
  },
];

async function main() {
  console.info('🌱 Seeding ShubhMilan database…');

  // Plans — seed defaults (matches prototype + spec §13)
  await prisma.plan.createMany({
    skipDuplicates: true,
    data: [
      { id: 'plan_free', name: 'Free Forever', priceInr: 0, durationDays: 36500, features: ['Create profile', 'Browse profiles', '5 interests/month', 'Basic chat'], active: true },
      { id: 'plan_silver', name: 'Silver', priceInr: 99900, durationDays: 90, features: ['All Free features', 'Unlimited interests', 'See who viewed you', 'Priority listing'], active: true },
      { id: 'plan_gold', name: 'Gold', priceInr: 199900, durationDays: 180, features: ['All Silver features', 'Verified badge', 'Contact details', 'Relationship manager'], active: true },
      { id: 'plan_platinum', name: 'Platinum', priceInr: 299900, durationDays: 365, features: ['All Gold features', 'Top highlight', 'Horoscope report', 'Wedding planner'], active: true },
    ],
  });
  console.info('   ✓ plans seeded');

  // Superadmin
  const adminHash = await bcrypt.hash('Admin#12345', 12);
  await prisma.user.upsert({
    where: { email: 'support@tenderfy.org' },
    update: {},
    create: {
      email: 'support@tenderfy.org',
      phone: '+919900000001',
      passwordHash: adminHash,
      role: 'SUPERADMIN',
      emailVerifiedAt: new Date(),
      phoneVerifiedAt: new Date(),
    },
  });
  console.info('   ✓ superadmin ensured (support@tenderfy.org / Admin#12345)');

  // Sample profiles
  const userHash = await bcrypt.hash('Demo#12345', 12);
  for (const s of SAMPLES) {
    const user = await prisma.user.upsert({
      where: { email: s.email },
      update: {},
      create: {
        email: s.email,
        phone: s.phone,
        passwordHash: userHash,
        emailVerifiedAt: new Date(),
        phoneVerifiedAt: new Date(),
      },
    });

    await prisma.profile.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        userId: user.id,
        fullName: s.fullName,
        gender: s.gender,
        dob: new Date(s.dob),
        height: s.height,
        maritalStatus: s.maritalStatus,
        motherTongue: s.motherTongue,
        religion: s.religion,
        caste: s.caste,
        subCaste: s.subCaste ?? null,
        gotra: s.gotra ?? null,
        manglik: s.manglik,
        rashi: s.rashi ?? null,
        nakshatra: s.nakshatra ?? null,
        education: s.education,
        occupation: s.occupation,
        income: s.income ?? null,
        city: s.city,
        state: s.state,
        country: s.country,
        diet: s.diet,
        smoking: s.smoking,
        drinking: s.drinking,
        aboutMe: s.aboutMe,
        familyValues: s.familyValues,
        personalityTraits: s.personalityTraits as Prisma.InputJsonValue,
        hobbies: s.hobbies as Prisma.InputJsonValue,
        languages: s.languages as Prisma.InputJsonValue,
        verification: {
          create: {
            emailVerified: true,
            phoneVerified: true,
            trustScore: 45,
            tier: 'VERIFIED',
          },
        },
        preference: {
          create: {
            ageMin: 24,
            ageMax: 34,
            religions: [s.religion] as Prisma.InputJsonValue,
            castes: [] as Prisma.InputJsonValue,
            motherTongues: [s.motherTongue] as Prisma.InputJsonValue,
            education: [] as Prisma.InputJsonValue,
            occupation: [] as Prisma.InputJsonValue,
            cities: [] as Prisma.InputJsonValue,
            diet: [s.diet] as Prisma.InputJsonValue,
          },
        },
      },
    });
  }

  console.info(`   ✓ ${SAMPLES.length} sample profiles seeded`);
  console.info('✅ Seed complete');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
